#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#nitrogen --restore

case $HOSTNAME in
    phobos)
        bspc monitor "Virtual-1" --rename "mid"
        bspc monitor "mid" -d I II III IV V VI VII VIII IX X

        bspc rule -a Gimp desktop='^5' state=floating follow=on
        bspc rule -a Emacs desktop='^5' state=tiled
        #bspc rule -a Alacritty desktop='^9' state=tiled
        bspc rule -a Chromium desktop='^2'
        bspc rule -a Brave-browser desktop='^2'
        bspc rule -a discord desktop='^9'
        bspc rule -a Element desktop='^9'
        bspc rule -a mpv desktop='^3'
        bspc rule -a Mumble desktop='^8'
        bspc rule -a mplayer2 state=floating
        bspc rule -a Kupfer.py focus=on
        bspc rule -a Screenkey manage=off

        bspc config border_width         0
        bspc config window_gap           0
        ;;
    neptune)
        bspc monitor "eDP-1" --rename "mid"
        bspc monitor "mid" -d I II III IV V VI VII VIII IX X

        bspc rule -a Gimp desktop='^5' state=floating follow=on
        bspc rule -a Emacs desktop='^5' state=tiled
        #bspc rule -a Alacritty desktop='^9' state=tiled
        bspc rule -a Chromium desktop='^2'
        bspc rule -a Brave-browser desktop='^2'
        bspc rule -a discord desktop='^9'
        bspc rule -a Element desktop='^9'
        bspc rule -a mpv desktop='^3'
        bspc rule -a Mumble desktop='^8'
        bspc rule -a mplayer2 state=floating
        bspc rule -a Kupfer.py focus=on
        bspc rule -a Screenkey manage=off

        bspc config border_width         0
        bspc config window_gap           0
        ;;
    earth)
        bspc monitor "LVDS-1" --rename "mid"
        bspc monitor "mid" -d I II III IV V VI VII VIII IX X

        bspc rule -a Gimp desktop='^5' state=floating follow=on
        bspc rule -a Emacs state=tiled
        bspc rule -a Alacritty state=tiled
        bspc rule -a Chromium desktop='^2'
        bspc rule -a Brave-browser desktop='^2'
        bspc rule -a discord desktop='^9'
        bspc rule -a Element desktop='^9'
        bspc rule -a mpv desktop='^3'
        bspc rule -a Mumble desktop='^8'
        bspc rule -a mplayer2 state=floating
        bspc rule -a Kupfer.py focus=on
        bspc rule -a Screenkey manage=off

        bspc config border_width         0
        bspc config window_gap           0
        ;;
    jupiter)
        bspc monitor "DP-2" --rename "left"
        bspc monitor "DP-4" --rename "mid"
        bspc monitor "DP-3" --rename "right"

        bspc monitor "left"      -d  I     II     III     IV   V
        bspc monitor "mid"       -d  VI    VII    VIII    IX   X
        bspc monitor "right"     -d  XI    XII    XIII    XIV  XV
        # bspc monitor "topleft"   -d  XVI   XVII   XVIII   XIX  XX
        # bspc monitor "topmid"    -d  XXI   XXII   XXIII   XXIV XXV
        # bspc monitor "topright"  -d  XXVI  XXVII  XXVIII  XXIX XXX

        # Order monitors for sane keybinds
        first=$(bspc query -M --names | sed -n 1p)
        [ "$first" = "left" ] || bspc monitor "$first" -s "left"

        second=$(bspc query -M --names | sed -n 2p)
        [ "$second" = "mid" ] || bspc monitor "$second" -s "mid"

        third=$(bspc query -M --names | sed -n 3p)
        [ "$third" = "right" ] || bspc monitor "$third" -s "right"

        # fourth=$(bspc query -M --names | sed -n 4p)
        # [ "$fourth" = "topleft" ] || bspc monitor "$fourth" -s "topleft"

        # fifth=$(bspc query -M --names | sed -n 5p)
        # [ "$fifth" = "topmid" ] || bspc monitor "$fifth" -s "topmid"

        # bspc rule -a Gimp desktop='^5' state=floating follow=on
        # bspc rule -a Emacs desktop='^5' state=tiled
        # #bspc rule -a Alacritty desktop='^9' state=tiled
        # bspc rule -a Chromium desktop='^1'
        # bspc rule -a Brave-browser desktop='^1'
        # bspc rule -a discord desktop='^7'
        # bspc rule -a Element desktop='^3'
        # bspc rule -a mpv desktop='^2'
        # bspc rule -a Mumble desktop='^4'
        # bspc rule -a mplayer2 state=floating
        # bspc rule -a Kupfer.py focus=on
        # bspc rule -a Screenkey manage=off
        bspc config border_width         3
        bspc config window_gap           3

        ;;
esac

#For polybar
bspc config top_padding 19

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
