#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#nitrogen --restore

case $HOSTNAME in
    phobos)
        bspc monitor "Virtual-1" --rename "mid"
        bspc monitor "mid" -d I II III IV V VI VII VIII IX X

        bspc rule -a Gimp desktop='^5' state=floating follow=on
        bspc rule -a Emacs desktop='^5' state=tiled
        #bspc rule -a Alacritty desktop='^9' state=tiled
        bspc rule -a Chromium desktop='^2'
        bspc rule -a Brave-browser desktop='^2'
        bspc rule -a discord desktop='^9'
        bspc rule -a Element desktop='^9'
        bspc rule -a mpv desktop='^3'
        bspc rule -a Mumble desktop='^8'
        bspc rule -a mplayer2 state=floating
        bspc rule -a Kupfer.py focus=on
        bspc rule -a Screenkey manage=off
        ;;
    neptune)
        bspc monitor "eDP-1" --rename "mid"
        bspc monitor "mid" -d I II III IV V VI VII VIII IX X

        bspc rule -a Gimp desktop='^5' state=floating follow=on
        bspc rule -a Emacs desktop='^5' state=tiled
        #bspc rule -a Alacritty desktop='^9' state=tiled
        bspc rule -a Chromium desktop='^2'
        bspc rule -a Brave-browser desktop='^2'
        bspc rule -a discord desktop='^9'
        bspc rule -a Element desktop='^9'
        bspc rule -a mpv desktop='^3'
        bspc rule -a Mumble desktop='^8'
        bspc rule -a mplayer2 state=floating
        bspc rule -a Kupfer.py focus=on
        bspc rule -a Screenkey manage=off
        ;;
    earth)
        bspc monitor "LVDS-1" --rename "mid"
        bspc monitor "mid" -d I II III IV V VI VII VIII IX X

        bspc rule -a Gimp desktop='^5' state=floating follow=on
        bspc rule -a Emacs state=tiled
        bspc rule -a Alacritty state=tiled
        bspc rule -a Chromium desktop='^2'
        bspc rule -a Brave-browser desktop='^2'
        bspc rule -a discord desktop='^9'
        bspc rule -a Element desktop='^9'
        bspc rule -a mpv desktop='^3'
        bspc rule -a Mumble desktop='^8'
        bspc rule -a mplayer2 state=floating
        bspc rule -a Kupfer.py focus=on
        bspc rule -a Screenkey manage=off
        ;;
    jupiter)
        bspc monitor "DisplayPort-1" --rename "left"
        bspc monitor "DisplayPort-2" --rename "mid"
        bspc monitor "DisplayPort-0" --rename "right"

        bspc monitor "left" -d I II III IV V VI VII VIII IX X
        bspc monitor "mid" -d XI XII XIII XIV XV XVI XVII XVIII XIX XX
        bspc monitor "right" -d XXI XXII XXIII XXIV XXV XXVI XXVII XXVIII XXIX XXX

        # bspc rule -a Gimp desktop='^5' state=floating follow=on
        # bspc rule -a Emacs desktop='^5' state=tiled
        # #bspc rule -a Alacritty desktop='^9' state=tiled
        # bspc rule -a Chromium desktop='^1'
        # bspc rule -a Brave-browser desktop='^1'
        # bspc rule -a discord desktop='^7'
        # bspc rule -a Element desktop='^3'
        # bspc rule -a mpv desktop='^2'
        # bspc rule -a Mumble desktop='^4'
        # bspc rule -a mplayer2 state=floating
        # bspc rule -a Kupfer.py focus=on
        # bspc rule -a Screenkey manage=off
        ;;
esac

#For polybar
bspc config top_padding 19

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
